### ISSUE TITLE
Return type of `Main.layoutManager.getWorkAreaForMonitor` is incorrect.

### ISSUE THREAD

**Issue by KSXGitHub** [gjsify/gnome-shell#17]
It is currently `void`.

**Comment by schnz** [comment]
Published a fix under as `@girs/gnome-shell@45.0.0-beta9`.

Alternatively, it is also possible to directly use the Workspace Manager without using the (manually typed) `gnome-shell` package.

```ts
import Shell from "gi://Shell";

Shell.Global.get().workspace_manager.get_active_workspace().get_work_area_for_monitor(index)
```
