### ISSUE TITLE
`_leftBox` and `_rightBox` should exist in `Main.panel`

### ISSUE THREAD

**Issue by KSXGitHub** [gjsify/gnome-shell#20]
I don't know if `_leftBox` and `_rightBox` exist in all instances of `Panel` or just `Main.panel`.

If they exist in all instances of `Panel`, you can simply add them to `Panel` interface.

If they are unique to `Main.panel`, you can do this:

```typescript
// main.d.ts
export declare const panel: Panel & {
  _leftBox: St.BoxLayout
  _rightBox: St.BoxLayout
}
```

**Comment by swsnr** [comment]
We have since moved to Gnome 46, so I am closing this issue.

Please do re-open if it is still relevant, and provide a pull request 🙂
