### ISSUE TITLE
GNOME 46?

### ISSUE THREAD

**Issue by swsnr** [gjsify/gnome-shell#21]
Hello,

I'm porting an extension to GNOME 46, and stumbled upon the changes in the notification types.  So, now I need to update the typings, but I'm unsure what the intended way forward is with this repo, since presumably more types than just the notification stuff are wrong now.

Should I just make a merge request with whatever changes I have as are needed for my extension?

Or do you intend to go over the whole typings and check them one by one against the current GNOME Shell code?

I'm asking because I can perfectly do the former, but the latter looks like an awful lot of work 😬

**Comment by schnz** [comment]
Related: #5 

I suppose this repository doesn't claim to be 100% complete nor to be 100% compatible with the upstream Gnome shell code.

[Quote](https://github.com/gjsify/gnome-shell/issues/5#issuecomment-1812753057) from the referenced issue:

> Totally get it if you're only contributing types that you need for your work. That's actually a great approach because it means those types are getting tested in real-world scenarios. If more folks did the same, we'd gradually build up a solid collection of types, covering the most commonly used ones.

> So, definitely, even smaller contributions are super valuable and much appreciated.

I can only agree with that approach so I would be more than happy to integrate whatever contribution you can provide for this package!

**Comment by JumpLink** [comment]
I have now at least updated the dependencies of GNOME 46, but only made sure that the types are accepted by tsc and not tested . I would be happy if you could correct other types you come across

**Comment by swsnr** [comment]
I'll go through everything I'm using in my extensions 👍
