### ISSUE TITLE
Template for official CLI

### ISSUE THREAD

**Issue by Tbhesswebber** [gjsify/gnome-shell#3]
It would be really nice to get the example here out of the box as an option for the template when scaffolding the application with the CLI - `gnome-extensions create --template typescript`

I looked for some documentation on how to create templates and saw nothing, but it seems that a lot of things surrounding extensions are missing.  If you have an idea of where to start looking, I'd be happy to contribute

**Comment by swsnr** [comment]
I have a personal template repository for Gnome shell extensions in Typescript, see https://github.com/swsnr/gnome-shell-extension-typescript-template

I am not sure how we could extend `gnome-extensions --create`; I guess we'd need to work with Gnome Shell upstream here.

If you'd to figure this out, please be our guest, but personally I don't have time to look into this. I guess the other contributors have neither, so I'm taking the liberty to close this as not planned.  Feel free to open again if you disagree.
